// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json_class_generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace OpenFoodFactsAPI
{
    public class Full
    {
        public int h { get; set; }
        public int w { get; set; }
    }

    public class Sizes
    {
        public Full full { get; set; }
    }

    public class FrontFr
    {
        public string y2 { get; set; }
        public string x1 { get; set; }
        public string angle { get; set; }
        public string imgid { get; set; }
        public string white_magic { get; set; }
        public string x2 { get; set; }
        public string normalize { get; set; }
        public string y1 { get; set; }
        public string rev { get; set; }
        public string geometry { get; set; }
        public Sizes sizes { get; set; }
    }

    public class Full2
    {
        public int h { get; set; }
        public int w { get; set; }
    }

    public class Sizes2
    {
        public Full2 full { get; set; }
    }

    public class Full3
    {
        public int w { get; set; }
        public int h { get; set; }
    }

    public class Sizes3
    {
        public Full3 full { get; set; }
    }

    public class Full4
    {
        public int w { get; set; }
        public int h { get; set; }
    }

    public class Sizes4
    {
        public Full4 full { get; set; }
    }

    
    public class Full5
    {
        public int w { get; set; }
        public int h { get; set; }
    }

    public class Sizes5
    {
        public Full5 full { get; set; }
    }

    public class NutritionFr
    {
        public string y1 { get; set; }
        public string normalize { get; set; }
        public string x2 { get; set; }
        public string rev { get; set; }
        public string geometry { get; set; }
        public Sizes5 sizes { get; set; }
        public string y2 { get; set; }
        public string x1 { get; set; }
        public string angle { get; set; }
        public string white_magic { get; set; }
        public string imgid { get; set; }
    }

    public class Full6
    {
        public int h { get; set; }
        public int w { get; set; }
    }

    public class Sizes6
    {
        public Full6 full { get; set; }
    }

    public class Full7
    {
        public int w { get; set; }
        public int h { get; set; }
    }

    public class Sizes7
    {
        public Full7 full { get; set; }
    }

    public class IngredientsFr
    {
        public string y2 { get; set; }
        public string x1 { get; set; }
        public string angle { get; set; }
        public string white_magic { get; set; }
        public string imgid { get; set; }
        public string normalize { get; set; }
        public string y1 { get; set; }
        public string x2 { get; set; }
        public string rev { get; set; }
        public Sizes7 sizes { get; set; }
        public string geometry { get; set; }
    }

    public class Full8
    {
        public int w { get; set; }
        public int h { get; set; }
    }

    public class Sizes8
    {
        public Full8 full { get; set; }
    }

    public class Images
    {
        public FrontFr front_fr { get; set; }
        public NutritionFr nutrition_fr { get; set; }
        public IngredientsFr ingredients_fr { get; set; }
    }

    public class Nutriments
    {
        public double sugars_serving { get; set; }
        public string carbohydrates { get; set; }
        public double salt_100g { get; set; }
        public double fat_100g { get; set; }
        public string carbohydrates_100g { get; set; }
        public string saturated_fat_value { get; set; }
        public string proteins_unit { get; set; }
        public double salt { get; set; }
        public double sugars_100g { get; set; }
        public double sugars { get; set; }
        public string energy_serving { get; set; }
        public string fat_unit { get; set; }
        public string energy { get; set; }
        public string nutrition_score_fr { get; set; }
        public string energy_100g { get; set; }
        public string nutrition_score_uk_100g { get; set; }
        public double salt_serving { get; set; }
        public string saturated_fat_unit { get; set; }
        public string fat_value { get; set; }
        public string salt_unit { get; set; }
        public string proteins { get; set; }
        public double proteins_100g { get; set; }
        public string carbohydrates_serving { get; set; }
        public double saturated_fat { get; set; }
        public string energy_unit { get; set; }
        public string fat { get; set; }
        public string fat_serving { get; set; }
        public string proteins_serving { get; set; }
        public string sodium_value { get; set; }
        public string salt_value { get; set; }
        public string sugars_value { get; set; }
        public string energy_value { get; set; }
        public double sodium_100g { get; set; }
        public string nutrition_score_uk { get; set; }
        public double sodium { get; set; }
        public double saturated_fat_100g { get; set; }
        public string nutrition_score_fr_100g { get; set; }
        public string carbohydrates_value { get; set; }
        public string carbohydrates_unit { get; set; }
        public double saturated_fat_serving { get; set; }
        public double sodium_serving { get; set; }
        public string proteins_value { get; set; }
        public string sugars_unit { get; set; }
        public string sodium_unit { get; set; }
    }

    public class NutrientLevels
    {
        public string saturated_fat { get; set; }
        public string salt { get; set; }
        public string fat { get; set; }
        public string sugars { get; set; }
    }

    public class Ingredient
    {
        public string percent { get; set; }
        public int rank { get; set; }
        public string id { get; set; }
        public string text { get; set; }
    }

    public class Languages
    {
        public int enFrench { get; set; }
    }

    public class LanguagesCodes
    {
        public int fr { get; set; }
    }

    public class Product
    {
        public string[] categories_prev_hierarchy { get; set; }
        public string[] entry_dates_tags { get; set; }
        public int serving_quantity { get; set; }
        public string _id { get; set; }
        public string pnns_groups_2 { get; set; }
        public string[] pnns_groups_2_tags { get; set; }
        public string[] languages_tags { get; set; }
        public object[] brands_debug_tags { get; set; }
        public string image_front_url { get; set; }
        public string stores { get; set; }
        public string origins { get; set; }
        public object[] product_name_fr_debug_tags { get; set; }
        public string generic_name_fr { get; set; }
        public int additives_old_n { get; set; }
        public object[] nutrition_data_per_debug_tags { get; set; }
        public object[] expiration_date_debug_tags { get; set; }
        public string[] codes_tags { get; set; }
        public string[] additives_debug_tags { get; set; }
        public string[] labels_hierarchy { get; set; }
        public object[] cities_tags { get; set; }
        public string[] informers_tags { get; set; }
        public string image_ingredients_small_url { get; set; }
        public string[] _keywords { get; set; }
        public string[] pnns_groups_1_tags { get; set; }
        public string nutrition_score_debug { get; set; }
        public Images images { get; set; }
        public string ingredients_text_debug { get; set; }
        public string last_editor { get; set; }
        public string[] allergens_hierarchy { get; set; }
        public object[] categories_debug_tags { get; set; }
        public string countries { get; set; }
        public string image_front_small_url { get; set; }
        public object[] stores_debug_tags { get; set; }
        public Nutriments nutriments { get; set; }
        public string[] countries_hierarchy { get; set; }
        public string lang { get; set; }
        public string[] languages_hierarchy { get; set; }
        public string expiration_date { get; set; }
        public int last_modified_t { get; set; }
        public string generic_name { get; set; }
        public NutrientLevels nutrient_levels { get; set; }
        public object[] origins_tags { get; set; }
        public string no_nutrition_data { get; set; }
        public int ingredients_from_palm_oil_n { get; set; }
        public int created_t { get; set; }
        public object[] labels_debug_tags { get; set; }
        public string[] last_image_dates_tags { get; set; }
        public string ingredients_n { get; set; }
        public int sortkey { get; set; }
        public string[] categories_tags { get; set; }
        public object[] countries_debug_tags { get; set; }
        public string ingredients_text_with_allergens { get; set; }
        public string pnns_groups_1 { get; set; }
        public object[] quantity_debug_tags { get; set; }
        public string emb_codes { get; set; }
        public string packaging { get; set; }
        public string emb_codes_orig { get; set; }
        public string image_nutrition_small_url { get; set; }
        public string[] correctors_tags { get; set; }
        public string[] traces_hierarchy { get; set; }
        public string[] stores_tags { get; set; }
        public string[] last_edit_dates_tags { get; set; }
        public string[] labels_prev_tags { get; set; }
        public string[] states_tags { get; set; }
        public string image_small_url { get; set; }
        public string quantity { get; set; }
        public string[] additives_old_tags { get; set; }
        public string image_ingredients_thumb_url { get; set; }
        public string[] ingredients_n_tags { get; set; }
        public object[] traces_debug_tags { get; set; }
        public string[] states_hierarchy { get; set; }
        public string[] labels_tags { get; set; }
        public object[] purchase_places_debug_tags { get; set; }
        public string states { get; set; }
        public string image_url { get; set; }
        public string link { get; set; }
        public string allergens { get; set; }
        public string[] labels_prev_hierarchy { get; set; }
        public string serving_size { get; set; }
        public string interface_version_created { get; set; }
        public string[] allergens_tags { get; set; }
        public string image_thumb_url { get; set; }
        public object[] unknown_nutrients_tags { get; set; }
        public string[] ingredients_ids_debug { get; set; }
        public string last_modified_by { get; set; }
        public string[] categories_hierarchy { get; set; }
        public int fruits_vegetables_nuts_100g_estimate { get; set; }
        public string interface_version_modified { get; set; }
        public string nutrition_grades { get; set; }
        public string nutrition_grade_fr { get; set; }
        public string[] purchase_places_tags { get; set; }
        public int rev { get; set; }
        public string[] ingredients_that_may_be_from_palm_oil_tags { get; set; }
        public string brands { get; set; }
        public string image_front_thumb_url { get; set; }
        public string[] countries_tags { get; set; }
        public string ingredients_text_fr { get; set; }
        public string code { get; set; }
        public string[] debug_param_sorted_langs { get; set; }
        public string ingredients_text_with_allergens_fr { get; set; }
        public string[] ingredients_tags { get; set; }
        public string[] brands_tags { get; set; }
        public string manufacturing_places { get; set; }
        public string lc { get; set; }
        public object[] manufacturing_places_tags { get; set; }
        public string image_ingredients_url { get; set; }
        public string product_name { get; set; }
        public string additives_prev { get; set; }
        public Ingredient[] ingredients { get; set; }
        public string[] nutrient_levels_tags { get; set; }
        public int additives_n { get; set; }
        public object[] emb_codes_tags { get; set; }
        public string[] packaging_tags { get; set; }
        public string[] traces_tags { get; set; }
        public string labels { get; set; }
        public string[] editors_tags { get; set; }
        public object[] emb_codes_debug_tags { get; set; }
        public string product_name_fr { get; set; }
        public string categories { get; set; }
        public string max_imgid { get; set; }
        public string purchase_places { get; set; }
        public string nutrition_data_per { get; set; }
        public string[] additives_prev_tags { get; set; }
        public int complete { get; set; }
        public int additives_prev_n { get; set; }
        public object[] manufacturing_places_debug_tags { get; set; }
        public string additives { get; set; }
        public string ingredients_text { get; set; }
        public string[] additives_tags { get; set; }
        public string[] nutrition_grades_tags { get; set; }
        public int nutrition_score_warning_no_fiber { get; set; }
        public object[] checkers_tags { get; set; }
        public string[] labels_next_hierarchy { get; set; }
        public string traces { get; set; }
        public string[] ingredients_debug { get; set; }
        public int completed_t { get; set; }
        public object[] ingredients_text_fr_debug_tags { get; set; }
        public object[] ingredients_from_palm_oil_tags { get; set; }
        public string image_nutrition_thumb_url { get; set; }
        public object[] packaging_debug_tags { get; set; }
        public object[] serving_size_debug_tags { get; set; }
        public string[] categories_prev_tags { get; set; }
        public string[] labels_next_tags { get; set; }
        public string creator { get; set; }
        public object[] lang_debug_tags { get; set; }
        public Languages languages { get; set; }
        public int last_image_t { get; set; }
        public string[] photographers_tags { get; set; }
        public object[] link_debug_tags { get; set; }
        public object[] generic_name_fr_debug_tags { get; set; }
        public int ingredients_from_or_that_may_be_from_palm_oil_n { get; set; }
        public int ingredients_that_may_be_from_palm_oil_n { get; set; }
        public LanguagesCodes languages_codes { get; set; }
        public object[] origins_debug_tags { get; set; }
        public string image_nutrition_url { get; set; }
        public string id { get; set; }
    }

    public class OpenFoodFactsProduct
    {
        public string status_verbose { get; set; }
        public Product product { get; set; }
        public int status { get; set; }
        public string code { get; set; }
    }

}
